# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 258)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.hostEdit = QtWidgets.QLineEdit(Dialog)
        self.hostEdit.setObjectName("hostEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.portEdit = QtWidgets.QLineEdit(Dialog)
        self.portEdit.setObjectName("portEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.DBNameEdit = QtWidgets.QLineEdit(Dialog)
        self.DBNameEdit.setObjectName("DBNameEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DBNameEdit)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginEdit = QtWidgets.QLineEdit(Dialog)
        self.loginEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginEdit.setObjectName("loginEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.loginEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passEdit = QtWidgets.QLineEdit(Dialog)
        self.passEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passEdit.setObjectName("passEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.passEdit)
        self.sslCheckBox = QtWidgets.QCheckBox(Dialog)
        self.sslCheckBox.setObjectName("sslCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.sslCheckBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.loginEdit, self.passEdit)
        Dialog.setTabOrder(self.passEdit, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.hostEdit)
        Dialog.setTabOrder(self.hostEdit, self.portEdit)
        Dialog.setTabOrder(self.portEdit, self.DBNameEdit)
        Dialog.setTabOrder(self.DBNameEdit, self.sslCheckBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Подключение к БД"))
        self.label_3.setText(_translate("Dialog", "сервер"))
        self.label_4.setText(_translate("Dialog", "порт"))
        self.label_5.setText(_translate("Dialog", "имя БД"))
        self.label.setText(_translate("Dialog", "логин"))
        self.label_2.setText(_translate("Dialog", "пароль"))
        self.sslCheckBox.setText(_translate("Dialog", "SSL шифрование"))
        self.pushButton.setText(_translate("Dialog", "Вход"))
