INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (1,14,N'Белгородская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (2,15,N'Брянская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (3,17,N'Владимирская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (4,20,N'Воронежская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (5,24,N'Ивановская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (6,29,N'Калужская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (7,34,N'Костромская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (8,38,N'Курская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (9,42,N'Липецкая область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (10,46,N'Московская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (11,54,N'Орловская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (12,61,N'Рязанская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (13,66,N'Смоленская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (14,68,N'Тамбовская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (15,28,N'Тверская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (16,70,N'Тульская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (17,78,N'Ярославская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (18,45,N'город Москва',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (19,9,N'Белгородская область',1,N'Центральный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (20,86,N'Республика Карелия',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (21,87,N'Республика Коми',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (22,11,N'Архангельская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (23,19,N'Вологодская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (24,27,N'Калининградская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (25,41,N'Ленинградская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (26,47,N'Мурманская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (27,49,N'Новгородская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (28,58,N'Псковская область',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (29,40,N'город Санкт-Петербург',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (30,11,N'Ненецкий автономный округ',2,N'Северо-Западный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (31,79,N'Республика Адыгея',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (32,85,N'Республика Калмыкия',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (33,3,N'Краснодарский край',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (34,12,N'Астраханская область',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (35,18,N'Волгоградская область',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (36,60,N'Ростовская область',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (38,82,N'Республика Дагестан',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (39,26,N'Республика Ингушетии',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (40,83,N'Кабардино-Балкарская Республика',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (41,91,N'Карачаево-Черкесская Республика',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (42,90,N'Республика Северная Осетия-Алания',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (43,96,N'Чеченская Республика',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (44,7,N'Ставропольский край',4,N'Северо–Кавказский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (45,80,N'Республика Башкортостан',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (46,88,N'Республика Марий Эл',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (47,89,N'Республика Мордовии',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (48,92,N'Республика Татарстан',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (49,94,N'Удмуртская Республики',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (50,97,N'Чувашская Республики',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (51,57,N'Пермский край',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (52,33,N'Кировская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (53,22,N'Нижегородская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (54,53,N'Оренбургская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (55,56,N'Пензенская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (56,36,N'Самарская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (57,63,N'Саратовская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (58,73,N'Ульяновская область',5,N'Приволжский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (59,37,N'Курганская область',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (60,65,N'Свердловская область',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (61,71,N'Тюменская область',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (62,75,N'Челябинская область',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (63,71,N'Ханты-Мансийский автономный округ - Югра',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (64,71,N'Ямало-Ненецкий автономный округ',6,N'Уральский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (65,84,N'Республика Алтай',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (66,81,N'Республика Бурятия',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (67,93,N'Республика Тыва',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (68,95,N'Республика Хакасия',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (69,1,N'Алтайский край',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (70,76,N'Забайкальский край',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (71,4,N'Красноярский край',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (72,25,N'Иркутская область',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (73,32,N'Кемеровская область',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (74,50,N'Новосибирская область',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (75,52,N'Омская область',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (76,69,N'Томская область',7,N'Сибирский федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (77,98,N'Республика Саха (Якутия)',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (78,30,N'Камчатский край',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (79,5,N'Приморский край',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (80,8,N'Хабаровский край',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (81,10,N'Амурская область',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (82,44,N'Магаданская область',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (83,64,N'Сахалинская область',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (84,99,N'Еврейская автономная область',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (85,77,N'Чукотский автономный округ',8,N'Дальневосточный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (86,35,N'Республика Крым',3,N'Южный федеральный округ');
INSERT `Regions` (`ID`,`OKTMO_ID`,`Name`,`FederalDistrictID`,`FederalDistrictName`) VALUES (87,67,N'город Севастополь',3,N'Южный федеральный округ');
