INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (1,N'г',N'город');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (2,N'пгт',N'поселок городского типа');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (3,N'рп',N'рабочий поселок');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (4,N'кп',N'курортный поселок');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (5,N'дп',N'дачный поселок');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (6,N'гп',N'городской поселок');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (7,N'п',N'поселок');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (8,N'к',N'кишлак');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (9,N'нп',N'населенный пункт');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (10,N'п.ст',N'поселок при станции (поселок станции)');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (11,N'п ж/д ст',N'поселок при железнодорожной станции');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (12,N'ж/д блокпост',N'железнодорожный блокпост');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (13,N'ж/д будка',N'железнодорожная будка');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (14,N'ж/д ветка',N'железнодорожная ветка');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (15,N'ж/д казарма',N'железнодорожная казарма');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (16,N'ж/д комбинат',N'железнодорожный комбинат');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (17,N'ж/д платформа',N'железнодорожная платформа');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (18,N'ж/д площадка',N'железнодорожная площадка');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (19,N'ж/д путевой пост',N'железнодорожный путевой пост');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (20,N'ж/д остановочный пункт',N'железнодорожный остановочный пункт');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (21,N'ж/д рзд',N'железнодорожный разъезд');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (22,N'ж/д ст',N'железнодорожная станция');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (23,N'м',N'местечко');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (24,N'д',N'деревня');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (25,N'с',N'село');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (26,N'сл',N'слобода');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (27,N'ст',N'станция');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (28,N'ст-ца',N'станица');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (29,N'у',N'улус');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (30,N'х',N'хутор');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (31,N'рзд',N'разъезд');
INSERT `SettlementTypes` (`ID`,`ShortName`,`Name`) VALUES (32,N'зим',N'зимовье');
